repos:
  # Git Commit Hook and common file formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*csv"
      - id: end-of-file-fixer
        exclude: ".*csv"
      - id: check-yaml
        args: [ "--unsafe" ] # Will not automatically commit changes after formatting

  # Sorting imports and removing unused imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

  # Black Formatting
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --line-length=120
          - --include='\.py?$'
          - --exclude=\.*
